# .github/workflows/deploy.yml
name: CI/CD

on:
  push:
    branches:
      - main # run only when main is updated

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up gcloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Set gcloud project
        run: gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

      - name: Configure docker auth
        run: gcloud auth configure-docker asia-southeast1-docker.pkg.dev --quiet

      - name: Build image
        run: |
          docker build -t asia-southeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/doo-doung/dd-be-1:latest .

      - name: Push image
        run: |
          docker push asia-southeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/doo-doung/dd-be-1:latest

      # optional: deploy to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy dd-be \
            --image asia-southeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/doo-doung/dd-be-1:latest \
            --region asia-southeast1 \
            --platform managed \
            --allow-unauthenticated
